name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        hadoop: [2.10.1, 3.3.0] # Consider adding 3.1.4 and 3.2.2.

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker-compose --file docker-compose.test.yml build --build-arg HADOOP_VERSION=${{ matrix.hadoop }}
          docker-compose --file docker-compose.test.yml run sut

  # Push image to GitHub Container Registry.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    strategy:
      matrix:
        hadoop: [2.10.1, 3.3.0] # Consider adding 3.1.4 and 3.2.2.

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          build-args: HADOOP_VERSION=${{ matrix.hadoop }}
          tags: ${{ github.repository }}

      - name: Push image
        run: |
          # Strip git ref prefix from version.
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name.
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention.
          [ "$VERSION" == "main" ] && VERSION=latest

          docker tag ${{ github.repository }} ghcr.io/${{ github.repository }}:$VERSION-hadoop${{ matrix.hadoop }}
          docker push ghcr.io/${{ github.repository }}:$VERSION-hadoop${{ matrix.hadoop }}

          docker tag ${{ github.repository }} jaconi/hadoop:$VERSION-hadoop${{ matrix.hadoop }}
          docker push jaconi/hadoop:$VERSION-hadoop${{ matrix.hadoop }}
